// Code generated by command: go run asm.go -out search_avx_amd64.s. DO NOT EDIT.

#include "textflag.h"

// func search(key *byte, nkey *[16]byte) uint16
// Requires: AVX, SSE2
TEXT ·search(SB), NOSPLIT, $0-18
	MOVQ     key+0(FP), AX
	MOVQ     nkey+8(FP), CX
	VPXOR    X1, X1, X1
	VMOVD    (AX), X0
	VPSHUFB  X1, X0, X0
	MOVOU    (CX), X1
	PCMPEQB  X1, X0
	PMOVMSKB X0, AX
	MOVW     AX, ret+16(FP)
	RET
